[workspace]
resolver = "3"
members = [
    "01_hello_window",
    "02_shader",
    "03_program",
    "04_context",
    "05_hello_triangle",
    "06_buffer",
    "07_texture",
    "08_transform",
    "09_camera",
]